version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    image: ds_django_postgres
    container_name: ds_django_postgres
    volumes:
      - django_data:/var/lib/postgresql/data:Z
      - django_data_backup:/backups:z
    env_file:
      - ../.env

  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    image: ds_django
    container_name: ds_django
    volumes:
      - ../django-website:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: ../.env
    ports:
      - "8000:8000"

volumes:
  django_data: {}
  django_data_backup: {}
