# Generated by Django 3.1.4 on 2021-01-04 20:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section_title', wagtail.core.fields.RichTextField(blank=True)),
                ('section_subtitle', wagtail.core.fields.RichTextField(blank=True)),
                ('linked_data', models.JSONField(blank=True, help_text='Linked Data in JSON', null=True)),
                ('main_subtitle', wagtail.core.fields.RichTextField(blank=True, help_text='Home Subtitle')),
                ('main_description', wagtail.core.fields.RichTextField(blank=True, help_text='Home Subtitle')),
                ('portfolio_title', wagtail.core.fields.RichTextField(blank=True)),
                ('portfolio_subtitle', wagtail.core.fields.RichTextField(blank=True)),
                ('about_title', wagtail.core.fields.RichTextField(blank=True)),
                ('about_subtitle', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
