# Generated by Django 3.1.4 on 2021-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210103_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='linked_data',
            field=models.JSONField(blank=True, help_text='Linked Data in JSON', null=True),
        ),
    ]
